### ISSUE TITLE
计算结果能不能返回所有结果

### ISSUE THREAD

**Issue by Rickion** [mumuy/relationship#10]
计算结果能不能返回所有称谓？比如"爷爷的父亲"，返回的是"曾祖父"，这里返回一个数组，把所有叫法都返回岂不更好

**Comment by mumuy** [comment]
不行，返回多个会被认为是多个关系结果，而“曾祖父”、“太爷”事实上表示同一个结果的不同称呼而已；
只有输入比如“表妹的妈妈”一样，返回“姑妈“、”舅妈“、”姨妈”这样的数组才是多个结果
