### ISSUE TITLE
建议把 relationship 改为 relation

### ISSUE THREAD

**Issue by AlumiK** [mumuy/relationship#13]
虽然 relationship 在字典上确实可以和 relation 通用但是在实际生活中的语言习惯上还是有区别。

blood relations 血缘关系
relations by marriage 婚姻关系

relationship 偏指感情而 relation 偏指联系。

例如：
The **relationship** between me and my father is good.
我和我的父亲**关系**很好。

The **relation** between me and this man is son and father.
这个人与我是父子**关系**。

**Comment by mumuy** [comment]
事实上亲戚关系应该用kinship这个单词，项目取名只是一个形式，relationship这个单词是我第一个想到的就用了，更易记
