### ISSUE TITLE
添加上“父”、“母”是否会更完整一些？

### ISSUE THREAD

**Issue by KavenFan** [mumuy/relationship#14]
relationship.js第186行：
    'f':['爸爸','父亲','阿爸','老爸','老窦','爸','爹','爹爹','爹地','爹啲','老爹','大大','老爷子','老头子'],
加上“父”

relationship.js第413行：
    'm':['妈妈','母亲','老妈','阿妈','老母','老妈子','娘','妈','娘亲','妈咪'],
加上“母”

是不是会更完善一些？

**Comment by mumuy** [comment]
已经增加
