### ISSUE TITLE
java版本亲戚关系

### ISSUE THREAD

**Issue by 13871007341** [mumuy/relationship#17]
老铁，因工作需要我改了个java版的，怎么提交呢？

**Comment by yinengp** [comment]
请问java版本能发我一份吗

**Comment by 2439905184** [comment]
fork，新建分支，提交pr

**Comment by mumuy** [comment]
额，我只开发JS版本，你开发Java版只能自己弄个仓库啦，我不会Java，也就不想维护Java版本了

**Comment by young2j** [comment]
需要golang和python版本的可以看这儿
https://github.com/young2j/relationship
