### ISSUE TITLE
计算不准

### ISSUE THREAD

**Issue by imisslovelove** [mumuy/relationship#22]
叫法与北方的叫法都对不上！

**Comment by mumuy** [comment]
一个关系有多个称呼，支持的是多称呼输入，输出统一采用较为常用的一个称呼。否则，如出现“姥姥的儿子的外婆的爹地”怎么办？各种地方称呼都有

**Comment by kissjin** [comment]
是的，爸爸的姐姐的儿子的儿子 给我回答了个 姑表侄男 ，这是个什么鬼

**Comment by kissjin** [comment]
不过这个idea还是不错的

**Comment by mumuy** [comment]
> 是的，爸爸的姐姐的儿子的儿子 给我回答了个 姑表侄男 ，这是个什么鬼

姑姑的儿子就是你的表哥或者表弟（姑表），哥哥的孩子是侄子，自然姑表哥的孩子是姑表侄了，侄分男女，男的就是侄男啊
