### ISSUE TITLE
请问是地方叫法不一样还是bug？

### ISSUE THREAD

**Issue by jdleung** [mumuy/relationship#25]
妈妈的姐妹的子女显示的是姨兄弟、姨姐妹，不是姨表兄弟、姨表姐妹吗？

**Comment by mumuy** [comment]
以前收录的是”姨表兄弟、姨表姐妹“，后来经过学习才知道，只有舅舅和姑姑家的才是”表“，姨妈家的叫”姨“或”从母“，和叔叔伯伯家的”堂“或”从父“相对应。”姨表“实际上是一个错误的说法，所以才修正的。

**Comment by jdleung** [comment]
> 以前收录的是”姨表兄弟、姨表姐妹“，后来经过学习才知道，只有舅舅和姑姑家的才是”表“，姨妈家的叫”姨“或”从母“，和叔叔伯伯家的”堂“或”从父“相对应。”姨表“实际上是一个错误的说法，所以才修正的。

哦原来这样。我们这里姨妈、姑妈，舅舅家的都叫“表”。如果改的话是否只更改分支前缀的 '{G1}' : 'm,xs'，还是 setMode 更改较为妥当？

另外，上一版本的“舅舅”变成了“大舅”、“小舅”，虽然一字之差，是否和“妻兄弟”的“大舅子”和“小舅子”有混淆？而且输入时是“妈妈的哥哥”也不一定是“大舅”，也可能是“二舅”、“三舅”，个人认为默认还是“舅舅”合适。

初次载入程序需要约9秒才能计算，这个怎样可以优化一下？

**Comment by mumuy** [comment]
'{G1}'中改，还要改replaceFilter中对'表'的定义，最好不要改，很多地方都叫表是因为很多人自己都分不清，按中国传统确实只有舅表和姑表。
setMode只是对特定关系的称呼覆盖，不改变内部对‘表’或‘堂’的定义；

对于排行并不印象称呼的理解，如果把‘舅舅’统一掉，对于年龄判断就会失衡了。“大舅”和“大舅子”有还挺好区分的，就像“小姨”和“小姨子”；“小姑”和“小姑子”；“大伯”和“大伯子”；本来就是差一辈的

**Comment by mumuy** [comment]
优化方面确实可以再想想，因为现在数据量大了，大部分关系是运行时生成的，还是会耗性能的

**Comment by jdleung** [comment]
收到，谢谢。

**Comment by mumuy** [comment]
确实有一个方法没写好，浪费了2.5秒，修复了；其他的慢是因为部署问题了，用Github pages部署的会有点慢
