### ISSUE TITLE
北方叫法

### ISSUE THREAD

**Issue by gggin** [mumuy/relationship#3]
在北方 作者可以了解一下北方的朋友
爸爸的哥哥 我们称作大爷 二大爷 三大爷 不叫伯父 希望可以增加南北叫法提示

**Comment by mumuy** [comment]
目前工具算法很难很好滴区分南北方，以及一些地方较少人叫的使用习惯，建议可以fork开发具有地区特色的版本吧

**Comment by gggin** [comment]
ok
