### ISSUE TITLE
不知道是Bug还是地方差异

### ISSUE THREAD

**Issue by HnHareJin** [mumuy/relationship#30]
<img width="476" alt="image" src="https://user-images.githubusercontent.com/11905702/176841705-0d9ea9a7-fe41-4cb3-9b17-0464333d4010.png">

输入：爸爸的哥哥的弟弟
输出：从父、爸爸
期望值：伯父、叔叔、爸爸

**Comment by mumuy** [comment]
感谢反馈，问题已修复。我期望值也是“伯父、叔叔、爸爸”，算法显示的是“伯父“和”叔叔”的合称，比较旧的叫法。

**Comment by HnHareJin** [comment]
> 感谢反馈，问题已修复。我期望值也是“伯父、叔叔、爸爸”，算法显示的是“伯父“和”叔叔”的合称，比较旧的叫法。

另外不知你是否能接受 TypeScript？我想后面有时间就把这个项目用 TypeScript 重构一下，JavaScript 可读性有点差

**Comment by mumuy** [comment]
太麻烦了，我比较习惯了直接写直接用的方式，尽量少依赖其他工具

**Comment by mumuy** [comment]
你可以试着fork下呀

**Comment by HnHareJin** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/11905702/178904568-eda904fd-176d-43c0-b7fc-382ff9528cc4.png">

今天又发现一个 Bug：
输入：爸爸的爸爸的兄弟的儿子
输出：从祖父
期望值：堂伯、堂叔

断点调试后发现和分支及分支前缀有关：
```
'{G2}':
  'f,f,xb': [ '从祖' ]
  'm,f,xb': [ '外从祖' ]

// 其他旁系
'{G2}': [ '祖父' ]
'{G2},w': [ '祖母' ]
'{G2},s': [ '父' ]
'{G2},s,w': [ '母' ]
'{G2},s,s&o': [ '兄' ]
'{G2},s,s&l': [ '弟' ]
'{G2},s,[s&o|s&l]': [ '兄弟' ]
'{G2},s,d&o': [ '姊' ]
'{G2},s,d&l': [ '妹' ]
'{G2},s,[d&o|d&l]': [ '姊妹' ]
'{G2},s,s,s': [ '男','子' ]
'{G2},s,s,d': [ '女' ]
```

应该是这里配置的问题，但我不知道此处配置会不会影响其他关系，所以没动代码

**Comment by mumuy** [comment]
最近把原有文件拆分了，如果你有什么数据要补充，欢迎提出来哦

**Comment by HnHareJin** [comment]
> 最近把原有文件拆分了，如果你有什么数据要补充，欢迎提出来哦

好的，谢谢！再有问题我会继续补充

**Comment by HnHareJin** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/11905702/179441678-7aedd824-d920-4fbc-a482-60e8167048b7.png">
<img width="484" alt="image" src="https://user-images.githubusercontent.com/11905702/179441985-8e601871-fd7f-49bd-8445-0559eb57d887.png">

输入：儿子的老婆的姐姐
输出：男眷女
期望值：姻侄女

我也搞不清楚 儿子的老婆的姐姐 应该叫什么才对，但我看小米计算器里面结果是姻侄女。而且 儿子的老婆的哥哥 输出为 姻侄，所以判断是缺陷

**Comment by HnHareJin** [comment]
另外在 afe84a6943fc6fa824dd7a76e3833ec619dd8974 这次提交中，
```javascript
-        '^([堂表姨]?)([曾高天烈太远鼻]?)(祖?)([伯叔姑舅姨])':['$1$4$2$3'],
+        '^([堂表姨]?)([曾高天烈太远鼻]?)([伯叔姑舅姨])':['$1$4$2$3'],
```
会导致正则分组数量不匹配的问题，按原来的逻辑应为：`$1$3$2`，已提交 PR

**Comment by mumuy** [comment]
“男眷女” 和“姻侄女”都是对的，只是“男眷女”更早期的叫法，偏书面；“姻侄女”更现代的叫法，更口语。小米用的是我早期的版本，可能是迭代过程中数据增删带来了差异，只有有一次把一些旁支信息都删除，用拼接的方式实现。现在已经补充上“姻侄女”的称呼了。

https://github.com/mumuy/relationship/commit/afe84a6943fc6fa824dd7a76e3833ec619dd8974  的提交应该是把“(祖?)”误删除了，没印象这里需要调整，就不合并PR了

**Comment by mumuy** [comment]
叫姻侄女应该是对的，亲家之间可以互相称姻兄弟，兄弟的孩子只要不是自己孩子的配偶，叫侄女没问题
