### ISSUE TITLE
错误了哦

### ISSUE THREAD

**Issue by boyfoo** [mumuy/relationship#36]
![63c44a12bf0b8514e6ab11b789061be](https://user-images.githubusercontent.com/29603067/212227566-fb357e45-8d87-4d3d-ba4d-a76b17d78496.png)

**Comment by mumuy** [comment]
没有错，你是不是按到了下面的⇌了，那个按键是切换对方叫你什么，关掉才是显示你叫对方什么

**Comment by mumuy** [comment]
你关掉那个⇌，就会显示“堂嫂/堂弟媳”
