### ISSUE TITLE
错误提示：relationship is not a function

### ISSUE THREAD

**Issue by vpanda666** [mumuy/relationship#37]
使用 import
import relationship from 'relationship.js';
或require
var relationship = require("relationship.js");
两个方式都不行，错误提示：
(0 , _relationship.default) is not a function

relationship is not a function

调用：relationship({text:'妈妈的妈妈的哥哥'});
语言：微信小程序+TS ，是TS，TS，不是JS

**Comment by mumuy** [comment]
我不做TS

**Comment by vpanda666** [comment]
哈喽 :) 我是一只有理想、有抱负、有灵魂的可爱大熊猫，您的微笑天使。[https://vpanda.net]
