### ISSUE TITLE
周瑜管夏侯惇叫什么

### ISSUE THREAD

**Issue by shenghaomail** [mumuy/relationship#38]
周瑜管夏侯惇叫什么？
经常在德云社的相声里听到这个梗，今天用计算器算了一下，结果是“--”
非抬杠，纯好奇

人物关系如下：
周瑜与孙策万千佳丽中寻得大乔小乔，周瑜娶了小乔，而孙策娶了大乔，成为姻亲。
孙策的妹妹孙尚香又嫁给了刘备做夫人，孙尚香强势断然不会为刘备生子，但刘备其他的儿子无疑也是孙尚香的子嗣，即刘禅。
刘禅所娶张皇后便是夏侯渊的侄女的女儿，即夏侯氏之女。
那么周瑜叫夏侯渊的哥哥夏侯惇什么呢?

**Comment by mumuy** [comment]
如果是说亲戚关系的话，没啥关系。因为周瑜并不是娶了小乔，而是纳妾。妾并不是妻子，而是一种性伴侣，也可以理解为女朋友。周瑜和孙策也算不是姻亲。

**Comment by Cairl** [comment]
> 周瑜管夏侯惇叫什么？ 经常在德云社的相声里听到这个梗，今天用计算器算了一下，结果是“--” 非抬杠，纯好奇
> 
> 人物关系如下： 周瑜与孙策万千佳丽中寻得大乔小乔，周瑜娶了小乔，而孙策娶了大乔，成为姻亲。 孙策的妹妹孙尚香又嫁给了刘备做夫人，孙尚香强势断然不会为刘备生子，但刘备其他的儿子无疑也是孙尚香的子嗣，即刘禅。 刘禅所娶张皇后便是夏侯渊的侄女的女儿，即夏侯氏之女。 那么周瑜叫夏侯渊的哥哥夏侯惇什么呢?

按现代的姻亲关系辈分来算，我们需要理清楚人物关系并进行推导。已知关系如下：

1. 周瑜和孙策分别娶了小乔和大乔。
2. 孙策的妹妹孙尚香嫁给了刘备。
3. 刘备的儿子刘禅娶了夏侯渊侄女的女儿，即夏侯氏之女。
4. 夏侯渊和夏侯惇是兄弟。

我们从周瑜的角度来分析与夏侯惇的关系：

1. 周瑜是孙策的连襟（周瑜娶了小乔，孙策娶了大乔）。
2. 孙尚香是周瑜的妻子小乔的小姑子。
3. 孙尚香嫁给刘备，刘备是孙尚香的丈夫，即孙策的妹夫。
4. 刘备的儿子刘禅是周瑜的妻子小乔的外甥（通过小乔的姐姐大乔的关系）。
5. 刘禅娶了夏侯渊侄女的女儿，即夏侯渊的孙女辈。
6. 夏侯渊和夏侯惇是兄弟，所以夏侯惇也是刘禅的远房长辈。

综合以上关系，用现代的姻亲辈分来看，周瑜和夏侯惇没有直接的血缘或姻亲关系。不过，若要以辈分称呼，考虑到夏侯惇是刘禅的长辈，而刘禅是通过婚姻关系与周瑜有间接关联的，周瑜可以称呼夏侯惇为“世伯”或“伯父”。

简而言之，按现代的姻亲辈分，周瑜称呼夏侯惇为“伯父”较为合适。——来自 ChatGPT-4o

**Comment by mumuy** [comment]
> > 周瑜管夏侯惇叫什么？ 经常在德云社的相声里听到这个梗，今天用计算器算了一下，结果是“--” 非抬杠，纯好奇
> > 人物关系如下： 周瑜与孙策万千佳丽中寻得大乔小乔，周瑜娶了小乔，而孙策娶了大乔，成为姻亲。 孙策的妹妹孙尚香又嫁给了刘备做夫人，孙尚香强势断然不会为刘备生子，但刘备其他的儿子无疑也是孙尚香的子嗣，即刘禅。 刘禅所娶张皇后便是夏侯渊的侄女的女儿，即夏侯氏之女。 那么周瑜叫夏侯渊的哥哥夏侯惇什么呢?
> 
> 按现代的姻亲关系辈分来算，我们需要理清楚人物关系并进行推导。已知关系如下：
> 
> 1. 周瑜和孙策分别娶了小乔和大乔。
> 2. 孙策的妹妹孙尚香嫁给了刘备。
> 3. 刘备的儿子刘禅娶了夏侯渊侄女的女儿，即夏侯氏之女。
> 4. 夏侯渊和夏侯惇是兄弟。
> 
> 我们从周瑜的角度来分析与夏侯惇的关系：
> 
> 1. 周瑜是孙策的连襟（周瑜娶了小乔，孙策娶了大乔）。
> 2. 孙尚香是周瑜的妻子小乔的小姑子。
> 3. 孙尚香嫁给刘备，刘备是孙尚香的丈夫，即孙策的妹夫。
> 4. 刘备的儿子刘禅是周瑜的妻子小乔的外甥（通过小乔的姐姐大乔的关系）。
> 5. 刘禅娶了夏侯渊侄女的女儿，即夏侯渊的孙女辈。
> 6. 夏侯渊和夏侯惇是兄弟，所以夏侯惇也是刘禅的远房长辈。
> 
> 综合以上关系，用现代的姻亲辈分来看，周瑜和夏侯惇没有直接的血缘或姻亲关系。不过，若要以辈分称呼，考虑到夏侯惇是刘禅的长辈，而刘禅是通过婚姻关系与周瑜有间接关联的，周瑜可以称呼夏侯惇为“世伯”或“伯父”。
> 
> 简而言之，按现代的姻亲辈分，周瑜称呼夏侯惇为“伯父”较为合适。——来自 ChatGPT-4o

大乔小乔是妾，妾在古代就是性伴侣，并不是妻子。就是说周瑜和小乔、孙策和大乔压根就不是夫妻关系！！！更没有连襟一说呀
