### ISSUE TITLE
关系不存在

### ISSUE THREAD

**Issue by BajaXX** [mumuy/relationship#39]
爸爸妈妈的姐姐的儿子  这个关系不存在，但是爸爸妈妈的姐姐的女儿可以计算出是姨姑母

**Comment by BajaXX** [comment]
在之前的版本中是存在这个关系的
'f,m,xs,s&o': ['姨伯父', '姨伯', '从母伯父'],
'f,m,xs,s&l': ['姨叔父', '姨叔', '从母叔父'],
但是在最近更新的版本中好像有些问题

**Comment by mumuy** [comment]
谢谢反馈，已修复；前段时间调整算法没想到判断有失误，单元测试没检查出来
