### ISSUE TITLE
爸爸的儿子的哥哥的弟弟的妹妹的姐姐的儿子

### ISSUE THREAD

**Issue by catboy1006** [mumuy/relationship#4]
应该是啥？为什么显示的舅舅

**Comment by mumuy** [comment]
你可能按到“对方称呼你”的地方了～我的程序显示：“爸爸的儿子的哥哥的弟弟的妹妹的姐姐的儿子 ”为“儿子或外甥”

**Comment by mumuy** [comment]
“爸爸的儿子的哥哥的弟弟的妹妹的姐姐的儿子 ”可以化为“爸爸的女儿的儿子”，那么如果自己是“女”的可能就是自己的儿子了，如果自己是“男”的就是外甥了

**Comment by mumuy** [comment]
我的程序看来还有点问题，选择自己性别在这种情况下无效，理论上如果自己性别选男的，是不应该有“儿子”这个选项的

**Comment by mumuy** [comment]
问题已修复！现在搜索“爸爸的儿子的哥哥的弟弟的妹妹的姐姐的儿子”，即“爸爸的女儿的儿子”，如果你的性别设置为男性的话，给出答案“外甥”，如果你的性别为女性的话，给出答案“儿子或外甥”
