### ISSUE TITLE
全新版本

### ISSUE THREAD

**Issue by zerosoul** [mumuy/relationship#45]
感谢作者，我二次开发了一个版本，基本上把relationship.js提供的特性用到了极致：

做了以下改进：
1. 修复了官方demo的一些bug，比如计算器“夫”“妻”disable规则问题（自动判断最后输入项的性别，官方demo只判断了首次输入的性别）
2. 新增根据语言描述找关系
3. 重构UI交互，尽可能做到交互自然

![image](https://github.com/mumuy/relationship/assets/2985895/9813f15d-5417-4db4-b119-6c131cee1dba)
![image](https://github.com/mumuy/relationship/assets/2985895/8b98f3a3-1b60-4cf0-afc3-126d80fe99c8)
<img width="258" alt="image" src="https://github.com/mumuy/relationship/assets/2985895/fa1426a5-1e1d-4362-8c1c-7e69a0c34c4e">

体验地址：https://sinqi.tools/calc/relationship

**Comment by mumuy** [comment]
你可以尝试下演示页面：https://passer-by.com/relationship/，并不是只在首次输入判断性别，每次输入都有判断性别，这个问题在很早的版本就已经处理过了；
