### ISSUE TITLE
请求增加 typescript 类型声明

### ISSUE THREAD

**Issue by whinc** [mumuy/relationship#47]
> 我最近在做一个计算器品类的小程序，其中的亲戚关系计算器使用这个库实现，节省了我大量的时间，并获得了可靠的质量，感谢 @mumuy 的辛勤付出和杰出的工作成果，等我发布更新后会在开源致谢页面附上 relationship 项目的地址和作者信息，再次感谢。

当前 relationship 使用纯 js 实现，缺少对 ts 的有效支持，导致在 js/ts 项目中通过 npm 包引入使用时无类型补全和检查，期望能补充 ts 的类型声明。

**Comment by whinc** [comment]
我提了 PR https://github.com/mumuy/relationship/pull/46 期待 @mumuy 进行 review

**Comment by mumuy** [comment]
那个……我挺不喜欢typescript的，不想加，只想要原生的

**Comment by whinc** [comment]
OK，我暂时关闭了本仓库的 PR，改为给 @types 提 PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67762 ，这样可以不影响本项目，如果 ts 项目中需要类型支持时，只需额外安装下面依赖即可

```bash
npm install -D @types/relationship.js 
```

**Comment by mumuy** [comment]
佩服！哈哈哈……所实话我还真不知道可以这么操作！学会了一个知识！

**Comment by whinc** [comment]
😄 🤝

**Comment by whinc** [comment]
> OK，我暂时关闭了本仓库的 PR，改为给 @types 提 PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67762 ，这样可以不影响本项目，如果 ts 项目中需要类型支持时，只需额外安装下面依赖即可
> 
> 
> 
> ```bash
> 
> npm install -D @types/relationship.js 
> 
> ```
> 
> 
> 
> 效果如下：
> 
> 
> 
> <img width="860" alt="image" src="https://github.com/mumuy/relationship/assets/5096493/e2fd19b8-dcc2-4358-b884-263b7ddf686c">
> 
> 
> 
> <img width="915" alt="image" src="https://github.com/mumuy/relationship/assets/5096493/757486d0-3e0c-4fea-97fb-f2498318a082">
> 
> 

@mumuy 已被合并，npm 上已经可以搜到了 [@types/relationship.js](https://www.npmjs.com/package/@types/relationship.js)

**Comment by mumuy** [comment]
哈哈哈，OK，我可以试试
