### ISSUE TITLE
api.github.com国内打开太慢了

### ISSUE THREAD

**Issue by 2days** [mumuy/relationship#52]
![QQ截图20231231184653](https://github.com/mumuy/relationship/assets/6368072/ce3ae294-0728-4ffa-a50c-e95ed4a501cc)
![QQ截图20231231184751](https://github.com/mumuy/relationship/assets/6368072/048062c1-7327-44a4-9b55-65e15d1dd4d2)
可不可以调用其他国内的啊

**Comment by mumuy** [comment]
调用不了
