### ISSUE TITLE
safari浏览器及部分ios机型报错

### ISSUE THREAD

**Issue by dadongfang** [mumuy/relationship#56]
1.2.6最新版本

SyntaxError: Invalid regular expression: invalid group specifier name
eval
./node_modules/relationship.js/dist/relationship.min.mjs — vendors~info_index.cb484f35.js:35
__webpack_require__ — app.41a7933b.js:1536
fn — app.41a7933b.js:257

**Comment by mumuy** [comment]
重新安装最新版试试……应该是正则表达式兼容问题，之前浏览器不支持正向肯定预查，我做了兼容。后来看浏览器都支持了，我就放开了，没想到还有浏览器这个不支持

**Comment by dadongfang** [comment]
最新版没问题了 @mumuy
