### ISSUE TITLE
我的node版本是22，出现这个错误

### ISSUE THREAD

**Issue by QiuFuren** [mumuy/relationship#58]
<img width="572" alt="8893f2bd1a59e1dca71ec9cae394e0b" src="https://github.com/user-attachments/assets/dbc835bd-f6ce-49bd-ae35-25537d289783">

**Comment by mumuy** [comment]
感谢反馈，是node新版本模板加载中语法有调整
原来
import xx from './package.json' assert { type:'json' }; 
改成了
import xx from './package.json' with { type:'json' }; 

已更新

**Comment by QiuFuren** [comment]
运行npm text是开始测试吗，但是我这里返回的是
<img width="530" alt="82211bb996b4b69023aede4a1257ca5" src="https://github.com/user-attachments/assets/cb2289ac-4e95-4a45-b1ec-abacdad123a2">
这样，这是正确的吗？
