### ISSUE TITLE
问个问题，假设是入赘的情况下如何变化关系呐？

### ISSUE THREAD

**Issue by wolfan** [mumuy/relationship#6]
虽然现代社会入赘的情况相对少了许多，但并未这样的关系关未消失。
那如何进行关系的转换呐？

此外还有过继也是相同的问题。

**Comment by mumuy** [comment]
这种情况不考虑！何况入赘不改变称呼啊！
还有人舅舅取了自己的姑妈的呢！只能一个关系一个称谓
