### ISSUE TITLE
代号

### ISSUE THREAD

**Issue by lvqiuyanwen** [mumuy/relationship#7]
'$1$2'$3
,xb 
“#”
等符号代表什么意思

**Comment by mumuy** [comment]
我用于存储任务关系的代号，f爸爸，m妈妈，h老公，w老婆，s儿子，d女儿，ob哥哥，lb弟弟，os姐姐，ls妹妹……然后用正则关系讲关系简化，比如爸爸的老婆就是妈妈，那么f,w替换成m

**Comment by mumuy** [comment]
我用于存储人物关系的代号，f爸爸，m妈妈，h老公，w老婆，s儿子，d女儿，ob哥哥，lb弟弟，os姐姐，ls妹妹……然后用正则关系讲关系简化，比如爸爸的老婆就是妈妈，那么f,w替换成m

**Comment by lvqiuyanwen** [comment]
嗯，我看懂了常用的关系。正则简化关系没看懂
如： {//如果自己是男性,父母的儿子是自己或者兄弟
            exp: /^(.*)(,[fh1]|[xol]b),[mf],s(.*)$/,
            str: '$1$2,xb$3#$1$2$3'
        },  这里 $1,$2,$3,# 是什么意思
另外 xb,xs 是哪种亲戚关系。
感谢指导。

**Comment by mumuy** [comment]
xb,xs是指兄弟姐妹，x表示没分年龄

**Comment by lvqiuyanwen** [comment]
好吧，能解释下
exp: /^(.)(,[fh1]|[xol]b),[mf],s(.)$/,
str: '$1$2,xb$3#$1$2$3'   // 这里的意思不  $1,$2,$3,#

**Comment by mumuy** [comment]
有可能是自己本身，有可能是自己的兄弟姐妹啊
