### ISSUE TITLE
中文数字

### ISSUE THREAD

**Issue by lvqiuyanwen** [mumuy/relationship#8]
str = str.replace(/[二|三|四|五|六|七|八|九|十]{1,2}/g, 'x');
开始分词解析的时候都是中文的称呼，把数字替换为x，比如二哥的。。就为x哥的。。 
然后x哥就在data中找不到对应的代号，就会忽略掉这一匹配?

**Comment by mumuy** [comment]
嗯嗯，目前只匹配x舅，x姨等等
